In [1]:
from terra_sdk.client.lcd import LCDClient
import terra_sdk
import pandas as pd
import numpy as np
import re
import requests
from tools import wallet_balance, return_transaction_data
terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")

## This notebook gives the tools to determine a wallets balance and transaction history

In [2]:
# Sets the numeric option to remove scientific notation
pd.set_option('display.float_format', lambda x: '%.6f' % x)

In [3]:
# Call to make sure you're getting information from the most current block
terra.tendermint.block_info()['block']['header']['height']

'6665747'

### Wallet Balance

In [4]:
wallet = 'terra1hd0wzl7j9665rxyluwuh6j8fzkskp72gxyur6h'
wallet2 = 'terra17yap3mhph35pcwvhza38c2lkj7gzywzy05h7l0'

In [5]:
# Gets the balance of any wallet address in bech32 format 
# on the terra blockchain 

wallet_balance(wallet2)

                                               denom         amount
0  ibc/0471F1C4E7AFD3F07702BEF6DC365268D64570F7C1...       0.070071
1  ibc/0A866A7A214C42CEF84430C8A4C7210C8C7A980548...       0.080183
2  ibc/2BBF3EEB88F4BB5285A5075DE1B40EF65E5028947B...       0.052306
3  ibc/763E49A7BBF4CDD21F3AF3BFB3566A25A846B77B6E...       0.006989
4  ibc/EB2CED20AB0466F18BE49285E56B31306D4C60438A...       1.942734
5  ibc/FA0006F056DB6719B8C16C551FC392B62F5729978F...       0.000373
6                                               uusd 9338056.214541

In [6]:
# Test the function 
wallet_balance('blue')

'Your entry must be a bech32 Terra address with a dtype str'

### Transaction History

In [7]:
AccountAddress = 'terra1rscyt97yl7lsevclv96323m5q3p3w5vsdjvnde'

In [8]:
return_transaction_data(AccountAddress)

,id,chainId,tx,logs,height,txhash,gas_used,gas_wanted
timestamp,,,,,,,,
2022-02-28 11:00:23+00:00,233656395,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6660303,E2CFFB347C197DA8224E0463701080490BD61CA1E70F26...,1706553,2537208
2022-02-28 10:16:59+00:00,233640668,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6659913,222A01FB5512B97A85EDCC64702ECCB04505F58B36D3BD...,1533229,2277226
2022-02-28 07:59:03+00:00,233588866,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': '0uusd'}, 'events': [{'type':...",6658665,3C448C1AB944F647B9545D3E38709D44FB393ED0EC520C...,63189,156445
2022-02-28 07:57:38+00:00,233588269,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6658652,BF02D322A03C974C6C6FDBDC53D675BB56C6B29D9D1317...,141383,229138
2022-02-28 07:56:52+00:00,233588040,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6658645,CDC6958D265B878530B045F5EAA1F52D2F10862CC890F5...,142635,231329
...,...,...,...,...,...,...,...,...
2022-02-25 01:07:35+00:00,231703423,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6615864,A10F1A5D98793083E25FB8801149B8FE651710E11E3B17...,124978,200371
2022-02-25 01:07:03+00:00,231703212,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6615859,1C035F311F5BE553FF717F42417C82A9079FB2B92D5257...,124694,199932
2022-02-24 22:33:26+00:00,231641338,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6614472,267E57171AF667C9C129A32F75E7550257A55372F1BC50...,58230848,87271050
2022-02-24 22:33:00+00:00,231641112,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6614468,1F158B16235821038C6329E108D81FB34A15BD2674D74B...,14059715,21049230
2022-02-24 22:32:28+00:00,231640934,columbus-5,"{'type': 'core/StdTx', 'value': {'fee': {'gas'...","[{'log': {'tax': ''}, 'events': [{'type': 'exe...",6614463,8FE695510CF9CACC089B951539516E4FE906E2C182E5B2...,218891,312246